services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/gutta_web?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=XjGFBR7DJy8ZMzv2qU9RTy2cSqhb8N499pOmDMfW0bc=
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gutta-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gutta_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gutta_web"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - gutta-network
    restart: unless-stopped

  db-admin:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - gutta-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  gutta-network:
    driver: bridge